---
- hosts: dev
  become: True
  tasks:
    - name: su
      command: sudo su -
    - name: create new deployment
      command: kubectl apply -f /home/ubuntu/deployment.yml
    - name: create new service
      command: kubectl apply -f /home/ubuntu/service.yml

