apiVersion: v1
kind: Deployment
metadata:
  name: websitedeployment
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata: 
      labels: 
        app: website
    spec: 
      containers:
      - name: website
        image: shivap95/web1:0.3
        ports:
        - containerPort: 80
        
